sudo: required
dist: bionic
language: csharp
mono: none
services: docker
before_install:
  - cd 02-RESTWithASP-NET5Udemy-Calculator/RESTWithASP-NET5Udemy
  - echo "We are in the right folder!"
script: 
  - docker-compose build 
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
   docker tag rest-with-asp-net-5-udemy-db:latest $DOCKER_USERNAME/rest-with-asp-net-5-udemy-db:$TRAVIS_JOB_ID;
   docker tag rest_with_asp_net_udemy:latest $DOCKER_USERNAME/rest_with_asp_net_udemy:$TRAVIS_JOB_ID;
   docker push $DOCKER_USERNAME/rest-with-asp-net-5-udemy-db:$TRAVIS_JOB_ID;
   docker push $DOCKER_USERNAME/rest_with_asp_net_udemy:$TRAVIS_JOB_ID;
  on:
    branch: master
notifications:
  email: false
