version: '3.4'

services:
  restwithasp-net5udemy:
    image: rest_with_asp_net_udemy:dev
    container_name: RESTWithASP-NET5Udemy
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "RESTWithASP-NET5Udemy"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - C:\desenvolvimento\API\RESTwithASP-NET5Udemy\RESTWithASP-NET5Udemy\02-RESTWithASP-NET5Udemy-Calculator\RESTWithASP-NET5Udemy\RESTWithASP-NET5Udemy:/app
      - C:\desenvolvimento\API\RESTwithASP-NET5Udemy\RESTWithASP-NET5Udemy\02-RESTWithASP-NET5Udemy-Calculator\RESTWithASP-NET5Udemy:/src
      - C:\Users\karol\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\karol\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/root/.nuget/fallbackpackages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/net6.0/RESTWithASP-NET5Udemy.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true